"""Security helpers for the WorkerHost Named Pipe control channel.

Policy (design §6.1, §11):
- The pipe name is generated by the worker as ``\\\\.\\pipe\\VibeOCR-{uuid}``.
  The client must not invent names; only worker-generated UUID names are
  accepted (prevents path traversal / pipe-name injection).
- The pipe's DACL allows only the current user SID.
- After connecting, the client sends a 256-bit session token; the server
  compares it in constant time and rejects mismatches before any RPC.

The Win32-specific DACL/SID plumbing lives in ``named_pipe.py`` (Task 1.3).
This module holds the platform-neutral primitives (token + name validation) so
they can be unit-tested without a live pipe.
"""

from __future__ import annotations

import hmac
import re
import secrets

# Pipe namespace + prefix. The server owns the suffix UUID.
_PIPE_PREFIX = "\\\\.\\pipe\\VibeOCR-"
# Canonical v4 UUID, lowercase dashed.
_UUID_RE = re.compile(
    r"^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
)
# A validated pipe name is exactly the prefix + one v4 UUID.
_PIPE_NAME_RE = re.compile(
    r"^\\\\\.\\pipe\\VibeOCR-[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
)

_TOKEN_BYTES = 32  # 256-bit session token
_HEX_RE = re.compile(r"^[0-9a-f]{64}$")


class SessionTokenError(ValueError):
    """A session token failed validation."""


class PipeNameError(ValueError):
    """A pipe name failed validation."""


def generate_session_token() -> str:
    """Return a freshly generated 256-bit session token as 64 lowercase hex chars."""
    return secrets.token_hex(_TOKEN_BYTES)


def _check_token_shape(token: str) -> None:
    if not isinstance(token, str) or not _HEX_RE.match(token):
        raise SessionTokenError(
            "session token must be 64 lowercase hex chars (256-bit)"
        )


def verify_session_token(client_token: str, expected_token: str) -> bool:
    """Constant-time equality check between two session tokens.

    Raises ``SessionTokenError`` if either token is malformed (wrong length,
    non-hex, empty). Returns True iff the tokens match.
    """
    _check_token_shape(client_token)
    _check_token_shape(expected_token)
    return hmac.compare_digest(client_token, expected_token)


def generate_pipe_name() -> str:
    """Generate a fresh worker-owned pipe name ``\\\\.\\pipe\\VibeOCR-{uuid}``."""
    import uuid

    return f"{_PIPE_PREFIX}{uuid.uuid4()}"


def validate_pipe_name(name: str) -> str:
    """Validate that ``name`` is a worker-generated pipe name.

    Rejects relative paths, absolute file paths, network paths, bare words,
    unknown prefixes, and non-UUID suffixes. Returns the name if valid.
    """
    if not isinstance(name, str):
        raise PipeNameError(f"pipe name must be a string, got {type(name).__name__}")
    if not _PIPE_NAME_RE.match(name):
        # Provide a helpful classification without echoing arbitrary input.
        lowered = name.lower()
        if "\\\\" in lowered and "pipe\\" not in lowered:
            reason = "not a pipe path"
        elif ":" in name[:3]:
            reason = "looks like a drive path, not a pipe"
        elif name.startswith("\\\\") and not name.startswith("\\\\.\\"):
            reason = "network path, not a local pipe"
        elif "\\" not in name and "/" not in name:
            reason = "bare word, not a pipe path"
        elif name.startswith(_PIPE_PREFIX) and not _UUID_RE.match(
            name[len(_PIPE_PREFIX):]
        ):
            reason = "VibeOCR prefix but non-UUID suffix"
        else:
            reason = "unknown prefix or malformed"
        raise PipeNameError(f"invalid pipe name ({reason})")
    return name


__all__ = [
    "PipeNameError",
    "SessionTokenError",
    "generate_pipe_name",
    "generate_session_token",
    "validate_pipe_name",
    "verify_session_token",
]
